### ISSUE TITLE
Termina el ejercicio!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m3-evaluacion-intermedia-LorenaBH#1]
Buen trabajo @LorenaBH  !

Algunas pistas para acabarlo:

- [x] Termina de añadir los elementos finales de la tarjeta de cada Pokemon: los tipos tienen que ser una lista,  no pueden ser h3 sueltos, recuerda que son elementos relacionados. Un OL o UL es lo suyo.
- [x] Utiliza el nombre del Pokemon para el Alt de la imagen
- [x] Usa el `id` de cada pokemon para el  `key` de react cuando mapeas y creas un listado de componentes
- [x] Añade estilos (un archivo sass o css por componente)
- [x] Revisa los metadatos en index.html (lang, title...)
- [x] Limpia e indenta el código
- [x] Publica en Github Pages
- [x] Elimina archivos sin usary sus referencias

Si tienes cualquier duda, avisa!

Al turrón

**Comment by LorenaBH** [comment]
Carlos, creo que ya está.
lo de los metadatos no lo entendí muy bien xq vi que estaban todos correctos. A no ser que te refieras a que tengo que cambiar el nombre... puede ser?

**Comment by oneeyedman** [comment]
Te he comentado varios puntos por slack, si quieres mañana nos sentamos y los vemos.

**Comment by LorenaBH** [comment]
Carlos, ya he hecho los issues. Porfi revisame a ver si están bien, sobretodo porque esta mañana te dije que sí a lo de los archivos sin usar y eliminarlos y cuando me he puesto a ello de repente no lo veía tan claro, todos los necesitaba.
Por otra parte he hecho push de master, pero veo que no se actualizan los commits en github aunque refresque. Es necesario que haga también push origin docs? con add y commit tambien? no lo suelo hacer y todavía no tengo interiorizado el modus operandi

**Comment by LorenaBH** [comment]
Los commits ya estan ;) sorry

**Comment by oneeyedman** [comment]
Siguen si estar todas las cosas hechas: mañana las volvemos a ver si quieres.

**Comment by oneeyedman** [comment]
Terminado! YAY!!!
